#!/usr/bin/env ansible-playbook
---
- name: setup server
  hosts: tserver
  vars:
    nginx_service_port: 9090
  tasks:
    - name: get nginx official signing key
      apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
      sudo: True

    - name: adding nginx official apt install source
      apt_repository: repo='deb http://nginx.org/packages/ubuntu/ trusty nginx' state=present
      sudo: True

    - name: install nginx, supervisor, mysql5.6 through apt
      apt:  pkg={{item}} update_cache=yes state=present cache_valid_time=3600
      sudo: True
      with_items:
        - nginx
        - supervisor
        - mysql-server-5.6

    - name: remove the default config for ngnix
      file:
        state: absent
        path: /etc/nginx/sites-enabled/default
      sudo: True

    - name: copy the sstest nginx configuration files
      copy: src={{ item.src }} dest={{ item.dest }}
      sudo: True
      with_items:
        - {src: ../nginx/nginx/nginx.conf, dest: /etc/nginx/nginx.conf}
        - {src: ../nginx/nginx/conf.d/default.conf, dest: /etc/nginx/conf.d/default.conf}
      notify: restart nginx

    - name: copy the sstest supervisor configuration file
      copy: src={{ item.src }} dest={{ item.dest }}
      sudo: True
      with_items:
        - {src: ../supervisor/supervisor/conf.d/todoapi.conf, dest: /etc/supervisor/conf.d/todoapi.conf}


  handlers:
    - name: restart nginx
      sudo: True
      service: name=nginx state=restarted